# Generated by Django 4.0.2 on 2022-02-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(blank=True, max_length=500)),
                ('dateOfBirth', models.DateField()),
                ('currencyBalance', models.FloatField()),
                ('pageVisitors', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderCreatedDate', models.DateField()),
                ('itemCount', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='customerApp.customer')),
            ],
        ),
    ]
