# Generated by Django 4.0.2 on 2022-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_alter_customer_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerId',
            field=models.CharField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
    ]
