# Generated by Django 4.0.2 on 2022-02-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0006_alter_customer_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customerId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CustomerOrder', to='customerApp.customer'),
        ),
    ]
