# Generated by Django 4.0.2 on 2022-02-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0007_remove_customerorder_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customerId',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='customerApp.customer'),
        ),
    ]
